# # import math

# # NUM = int(input('Digite o numero: '))

# # raiz = math.sqrt(NUM)

# # print(math.ceil(raiz))



# # import emoji 

# # print(emoji.emoji('OLÁ mundo :sunglasses', use_aliases=true))


# nomes = ["Ana", "Pedro", "Lucas"]
# idades = [12, 14, 11]

# for nome, idade in zip(nomes, idades):
#     print(f"{nome} tem {idade} anos.")


# matriz = [
#     [1, 2, 3],
#     [4, 5, 6],
#     [7, 8, 9]
# ]

# for linha in matriz:  # Percorre cada linha da matriz
#     for elemento in linha:  # Percorre cada elemento da linha
#         print(elemento, end=" ")
#     print()  # Pula para a próxima linha
 

dados = {"nome": "Matheus", "idade": 22}

print(dados.get("nome"))  # Saída: Matheus


